server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/university?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zrzring
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
